### ISSUE TITLE
Instructor Feedback - Week 7 - Auth

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [SheepAntler/practiceHackerTracker#5]
Great job implementing tomcat's jdbc realm auth in your project!

- [x] As you continue adding functionality, remember to add any new resources that need to be restricted to the web.xml, including the servlets that do the real work (a savvy user might try to bypass the jsps and go directly to there servlets).

**Comment by SheepAntler** [comment]
Will do--thank you!
